# Generated by Django 4.1.7 on 2023-03-09 14:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('slug', models.SlugField(max_length=500, null=True)),
                ('image', models.ImageField(default='category_image.png', null=True, upload_to='category_images')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('slug', models.SlugField(max_length=500, null=True)),
                ('body', ckeditor.fields.RichTextField()),
                ('date_created', models.DateField(auto_now=True)),
                ('featured_image', models.ImageField(null=True, upload_to='poem_images')),
                ('add_to_featured_poems', models.BooleanField(default=True)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poem_castle.collection')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
