# Generated by Django 4.1.7 on 2023-03-11 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem_castle', '0002_alter_collection_image_alter_collection_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.RemoveField(
            model_name='collection',
            name='image',
        ),
        migrations.AddField(
            model_name='poem',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poem_castle.author'),
        ),
    ]
