# Generated by Django 4.1.7 on 2023-03-13 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem_castle', '0003_author_remove_collection_image_poem_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poem',
            options={'ordering': ['date_created']},
        ),
    ]
