# Generated by Django 4.1.7 on 2023-03-18 17:45

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem_castle', '0004_alter_poem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name='poem',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='poem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='poem_castle_search__ddde19_gin'),
        ),
    ]
